2023-07-08 00:13:53,631 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for abc.localhost
2023-07-08 00:13:53,634 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for abc.localhost
2023-07-08 00:13:53,636 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for abc.localhost
2023-07-08 00:13:53,638 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for abc.localhost
2023-07-08 00:13:53,639 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for abc.localhost
2023-07-08 00:14:53,963 ERROR scheduler Exception in Enqueue Events for Site abc.localhost
Traceback (most recent call last):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 68, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 118, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 787, in get_single_value
    ).run()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/query_builder/utils.py", line 86, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 209, in sql
    self.connect()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 124, in connect
    self._conn = self.get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 102, in get_connection
    conn = self._get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 108, in _get_connection
    return self.create_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 111, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'becky'@'localhost' (using password: NO)")
2023-07-08 00:15:54,022 ERROR scheduler Exception in Enqueue Events for Site abc.localhost
Traceback (most recent call last):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 68, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 118, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 787, in get_single_value
    ).run()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/query_builder/utils.py", line 86, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 209, in sql
    self.connect()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 124, in connect
    self._conn = self.get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 102, in get_connection
    conn = self._get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 108, in _get_connection
    return self.create_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 111, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'becky'@'localhost' (using password: NO)")
2023-07-08 00:16:54,085 ERROR scheduler Exception in Enqueue Events for Site abc.localhost
Traceback (most recent call last):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 68, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 118, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 787, in get_single_value
    ).run()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/query_builder/utils.py", line 86, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 209, in sql
    self.connect()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 124, in connect
    self._conn = self.get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 102, in get_connection
    conn = self._get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 108, in _get_connection
    return self.create_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 111, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'becky'@'localhost' (using password: NO)")
2023-07-08 00:17:54,149 ERROR scheduler Exception in Enqueue Events for Site abc.localhost
Traceback (most recent call last):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 68, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 118, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 787, in get_single_value
    ).run()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/query_builder/utils.py", line 86, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 209, in sql
    self.connect()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 124, in connect
    self._conn = self.get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 102, in get_connection
    conn = self._get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 108, in _get_connection
    return self.create_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 111, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'becky'@'localhost' (using password: NO)")
2023-07-08 00:18:54,217 ERROR scheduler Exception in Enqueue Events for Site abc.localhost
Traceback (most recent call last):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 68, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 118, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 787, in get_single_value
    ).run()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/query_builder/utils.py", line 86, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 209, in sql
    self.connect()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 124, in connect
    self._conn = self.get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 102, in get_connection
    conn = self._get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 108, in _get_connection
    return self.create_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 111, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'becky'@'localhost' (using password: NO)")
2023-07-08 00:19:54,282 ERROR scheduler Exception in Enqueue Events for Site abc.localhost
Traceback (most recent call last):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 68, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 118, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 787, in get_single_value
    ).run()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/query_builder/utils.py", line 86, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 209, in sql
    self.connect()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 124, in connect
    self._conn = self.get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 102, in get_connection
    conn = self._get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 108, in _get_connection
    return self.create_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 111, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'becky'@'localhost' (using password: NO)")
2023-07-08 00:20:54,349 ERROR scheduler Exception in Enqueue Events for Site abc.localhost
Traceback (most recent call last):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 68, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 118, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 787, in get_single_value
    ).run()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/query_builder/utils.py", line 86, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 209, in sql
    self.connect()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 124, in connect
    self._conn = self.get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 102, in get_connection
    conn = self._get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 108, in _get_connection
    return self.create_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 111, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'becky'@'localhost' (using password: NO)")
2023-07-08 00:21:54,413 ERROR scheduler Exception in Enqueue Events for Site abc.localhost
Traceback (most recent call last):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 68, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 118, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 787, in get_single_value
    ).run()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/query_builder/utils.py", line 86, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 209, in sql
    self.connect()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 124, in connect
    self._conn = self.get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 102, in get_connection
    conn = self._get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 108, in _get_connection
    return self.create_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 111, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'becky'@'localhost' (using password: NO)")
2023-07-08 00:22:54,477 ERROR scheduler Exception in Enqueue Events for Site abc.localhost
Traceback (most recent call last):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 68, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 118, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 787, in get_single_value
    ).run()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/query_builder/utils.py", line 86, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 209, in sql
    self.connect()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 124, in connect
    self._conn = self.get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 102, in get_connection
    conn = self._get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 108, in _get_connection
    return self.create_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 111, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'becky'@'localhost' (using password: NO)")
2023-07-08 00:23:54,541 ERROR scheduler Exception in Enqueue Events for Site abc.localhost
Traceback (most recent call last):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 68, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 118, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 787, in get_single_value
    ).run()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/query_builder/utils.py", line 86, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 209, in sql
    self.connect()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 124, in connect
    self._conn = self.get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 102, in get_connection
    conn = self._get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 108, in _get_connection
    return self.create_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 111, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'becky'@'localhost' (using password: NO)")
2023-07-08 00:24:54,605 ERROR scheduler Exception in Enqueue Events for Site abc.localhost
Traceback (most recent call last):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 68, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 118, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 787, in get_single_value
    ).run()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/query_builder/utils.py", line 86, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 209, in sql
    self.connect()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 124, in connect
    self._conn = self.get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 102, in get_connection
    conn = self._get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 108, in _get_connection
    return self.create_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 111, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'becky'@'localhost' (using password: NO)")
2023-07-08 00:25:54,669 ERROR scheduler Exception in Enqueue Events for Site abc.localhost
Traceback (most recent call last):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 68, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 118, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 787, in get_single_value
    ).run()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/query_builder/utils.py", line 86, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 209, in sql
    self.connect()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 124, in connect
    self._conn = self.get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 102, in get_connection
    conn = self._get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 108, in _get_connection
    return self.create_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 111, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'becky'@'localhost' (using password: NO)")
2023-07-08 00:26:54,733 ERROR scheduler Exception in Enqueue Events for Site abc.localhost
Traceback (most recent call last):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 68, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 118, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 787, in get_single_value
    ).run()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/query_builder/utils.py", line 86, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 209, in sql
    self.connect()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 124, in connect
    self._conn = self.get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 102, in get_connection
    conn = self._get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 108, in _get_connection
    return self.create_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 111, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'becky'@'localhost' (using password: NO)")
2023-07-08 00:27:54,803 ERROR scheduler Exception in Enqueue Events for Site abc.localhost
Traceback (most recent call last):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 68, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 118, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 787, in get_single_value
    ).run()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/query_builder/utils.py", line 86, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 209, in sql
    self.connect()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 124, in connect
    self._conn = self.get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 102, in get_connection
    conn = self._get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 108, in _get_connection
    return self.create_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 111, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'becky'@'localhost' (using password: NO)")
2023-07-08 00:28:54,865 ERROR scheduler Exception in Enqueue Events for Site abc.localhost
Traceback (most recent call last):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 68, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 118, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 787, in get_single_value
    ).run()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/query_builder/utils.py", line 86, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 209, in sql
    self.connect()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 124, in connect
    self._conn = self.get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 102, in get_connection
    conn = self._get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 108, in _get_connection
    return self.create_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 111, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'becky'@'localhost' (using password: NO)")
2023-07-08 00:29:54,933 ERROR scheduler Exception in Enqueue Events for Site abc.localhost
Traceback (most recent call last):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 68, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 118, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 787, in get_single_value
    ).run()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/query_builder/utils.py", line 86, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 209, in sql
    self.connect()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 124, in connect
    self._conn = self.get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 102, in get_connection
    conn = self._get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 108, in _get_connection
    return self.create_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 111, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'becky'@'localhost' (using password: NO)")
2023-07-08 00:30:54,998 ERROR scheduler Exception in Enqueue Events for Site abc.localhost
Traceback (most recent call last):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 68, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 118, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 787, in get_single_value
    ).run()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/query_builder/utils.py", line 86, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 209, in sql
    self.connect()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 124, in connect
    self._conn = self.get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 102, in get_connection
    conn = self._get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 108, in _get_connection
    return self.create_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 111, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'becky'@'localhost' (using password: NO)")
2023-07-08 00:31:55,064 ERROR scheduler Exception in Enqueue Events for Site abc.localhost
Traceback (most recent call last):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 68, in enqueue_events_for_site
    if is_scheduler_inactive():
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 105, in is_scheduler_inactive
    if is_scheduler_disabled(verbose=verbose):
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/utils/scheduler.py", line 118, in is_scheduler_disabled
    frappe.db.get_single_value("System Settings", "enable_scheduler")
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 787, in get_single_value
    ).run()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/query_builder/utils.py", line 86, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 209, in sql
    self.connect()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/database.py", line 124, in connect
    self._conn = self.get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 102, in get_connection
    conn = self._get_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 108, in _get_connection
    return self.create_connection()
  File "/home/becky/Desktop/new-frappe/apps/frappe/frappe/database/mariadb/database.py", line 111, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/becky/Desktop/new-frappe/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'becky'@'localhost' (using password: NO)")
2023-07-08 00:33:55,319 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for abc.localhost
2023-07-08 00:33:55,321 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for abc.localhost
2023-07-08 00:33:55,323 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for abc.localhost
2023-07-08 00:34:55,427 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for abc.localhost
2023-07-08 00:34:55,430 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for abc.localhost
2023-07-08 00:34:55,432 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for abc.localhost
2023-07-08 00:35:55,528 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for abc.localhost
2023-07-08 00:35:55,530 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for abc.localhost
2023-07-08 00:35:55,533 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for abc.localhost
2023-07-08 00:36:55,655 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for abc.localhost
2023-07-08 00:36:55,658 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for abc.localhost
2023-07-08 00:36:55,660 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for abc.localhost
2023-07-08 01:01:59,210 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for abc.localhost
2023-07-08 01:01:59,212 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for abc.localhost
2023-07-08 01:01:59,214 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for abc.localhost
2023-07-08 01:02:59,309 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for abc.localhost
2023-07-08 01:02:59,311 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for abc.localhost
2023-07-08 01:02:59,313 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for abc.localhost
2023-07-08 01:03:59,502 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for abc.localhost
2023-07-08 01:03:59,512 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for abc.localhost
2023-07-08 01:03:59,517 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for abc.localhost
2023-07-08 01:04:59,785 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for abc.localhost
2023-07-08 01:04:59,816 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for abc.localhost
2023-07-08 01:04:59,819 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for abc.localhost
2023-07-08 01:13:01,267 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for abc.localhost
2023-07-08 01:13:01,273 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for abc.localhost
2023-07-08 01:13:01,278 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for abc.localhost
2023-07-08 01:13:01,307 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for abc.localhost
2023-07-08 01:13:01,311 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for abc.localhost
2023-07-08 01:14:01,571 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for abc.localhost
2023-07-08 01:14:01,597 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for abc.localhost
2023-07-08 01:14:01,603 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for abc.localhost
2023-07-08 01:14:01,606 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for abc.localhost
2023-07-08 01:14:01,611 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for abc.localhost
2023-07-08 01:15:01,890 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for abc.localhost
2023-07-08 01:15:01,897 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for abc.localhost
2023-07-08 01:15:01,904 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for abc.localhost
2023-07-08 01:15:01,932 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for abc.localhost
2023-07-08 01:15:01,936 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for abc.localhost
2023-07-08 01:31:05,015 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for abc.localhost
2023-07-08 01:31:05,055 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for abc.localhost
2023-07-08 01:31:05,063 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for abc.localhost
2023-07-08 23:01:31,744 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for abc.localhost
2023-07-08 23:01:31,836 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for abc.localhost
2023-07-08 23:01:31,839 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for abc.localhost
2023-07-10 08:56:07,614 ERROR scheduler Skipped queueing frappe.email.doctype.auto_email_report.auto_email_report.send_daily because it was found in queue for abc.localhost
2023-07-10 08:56:07,881 ERROR scheduler Skipped queueing frappe.integrations.doctype.s3_backup_settings.s3_backup_settings.take_backups_daily because it was found in queue for abc.localhost
2023-07-10 08:56:07,885 ERROR scheduler Skipped queueing frappe.utils.change_log.check_for_update because it was found in queue for abc.localhost
2023-07-10 08:56:07,890 ERROR scheduler Skipped queueing frappe.integrations.doctype.dropbox_settings.dropbox_settings.take_backups_daily because it was found in queue for abc.localhost
2023-07-10 08:56:08,105 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for abc.localhost
2023-07-10 08:56:08,107 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for abc.localhost
2023-07-10 08:56:08,109 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for abc.localhost
2023-07-10 08:57:08,179 ERROR scheduler Skipped queueing frappe.email.doctype.auto_email_report.auto_email_report.send_daily because it was found in queue for abc.localhost
2023-07-10 08:57:08,181 ERROR scheduler Skipped queueing frappe.integrations.doctype.s3_backup_settings.s3_backup_settings.take_backups_daily because it was found in queue for abc.localhost
2023-07-10 08:57:08,182 ERROR scheduler Skipped queueing frappe.utils.change_log.check_for_update because it was found in queue for abc.localhost
2023-07-10 08:57:08,184 ERROR scheduler Skipped queueing frappe.integrations.doctype.dropbox_settings.dropbox_settings.take_backups_daily because it was found in queue for abc.localhost
2023-07-10 08:57:08,195 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for abc.localhost
2023-07-10 08:57:08,197 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for abc.localhost
2023-07-10 08:57:08,199 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for abc.localhost
2023-07-10 08:57:08,200 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for abc.localhost
2023-07-10 08:57:08,202 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for abc.localhost
2023-07-10 08:57:08,205 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for abc.localhost
2023-07-10 08:57:08,207 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for abc.localhost
2023-07-10 08:57:08,208 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for abc.localhost
